### ISSUE TITLE
Ppos模块调用getCandidateList/getValidatorList等方法时报出json处理相关的错误

### ISSUE THREAD

**Issue by joyceqingling** [PlatONnetwork/client-sdk-python#49]
我使用的是0.15.1的client-sdk-python，最近发现我的监控程序在调用getCandidateList/getValidatorList等方法时报错，见下图

![image](https://user-images.githubusercontent.com/58079255/119353421-71e7ba80-bcd5-11eb-9e58-6dec601f3187.png)

![image](https://user-images.githubusercontent.com/58079255/119353332-554b8280-bcd5-11eb-92d7-de700a10cd1a.png)

报错信息显示是处理json格式数据时出错

**Comment by liyuanchaoCh** [comment]
问题已确认并已经修复完毕。
bug原因：由于底层返回来的json串做了不必要的处理，导致序列化时出错。
影响范围：仅为ppos交易。
